apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # 重写路径，将/gateway和/agent重写为/
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /gateway(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-gateway
            port:
              number: 8080
      - path: /agent
        pathType: Prefix
        backend:
          service:
            name: app-agent
            port:
              number: 8080
